# Stage 1: Building the code
FROM node:latest as build

# Set the working directory in the Docker container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock) to the Docker image
COPY package*.json ./

# Install dependencies in the container
RUN npm install

# Copy the React source code into the container
COPY . .

# Build the React application
RUN npm run build

# Stage 2: Serve the app using nginx
FROM nginx:alpine

# Copy the custom Nginx config
# COPY custom-nginx.conf /etc/nginx/nginx.conf

# Copy the build output to replace the default nginx contents.
COPY --from=build /app/build /usr/share/nginx/html

# Expose the new port
EXPOSE 81

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
