name: Deploy to Ubuntu VPS

on:
  push:
    branches:
      - dev  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: dfanso/cine-magic:latest 
        build-args: |
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          GMAIL_USER=${{ secrets.GMAIL_USER }}
          GMAIL_PASS=${{ secrets.GMAIL_PASS }}
          EMAIL_FROM_ADDRESS=${{ secrets.EMAIL_FROM_ADDRESS }}
          PAYPAL_CLIENT_SECRET=${{ secrets.PAYPAL_CLIENT_SECRET }}
          PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}
          WEBHOOK_ID=${{ secrets.WEBHOOK_ID }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
          OMDB_API_KEY=${{ secrets.OMDB_API_KEY }}
          FRONTEND_URL=${{ secrets.FRONTEND_URL }}


    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }} 
        script: | 
          docker pull dfanso/cine-magic:latest
          docker stop cine-magic || true
          docker rm cine-magic || true
          docker run -d --name cine-magic -p 3000:3000 dfanso/cine-magic:latest