import { Logger, Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import * as Joi from 'joi';
import { ulid } from 'ulid';
import { ConfigModule } from '@nestjs/config';
import { MongooseModule, MongooseModuleOptions } from '@nestjs/mongoose';
import { ClsModule } from 'nestjs-cls';
import { AuthModule } from './auth/auth.module';
import { UsersModule } from './users/users.module';
import { EmailModule } from './email/email.module';
import { MoviesModule } from './movies/movies.module';
import { ShowTimesModule } from './show-times/show-times.module';
import { PaypalModule } from './paypal/paypal.module';
import { BookingModule } from './booking/booking.module';
import mongoose from 'mongoose';
import { ScheduleModule } from '@nestjs/schedule';
import { FeedbacksModule } from './feedbacks/feedbacks.module';
import { ChatModule } from './chat/chat.module';
import { S3Module } from './s3/s3.module';

mongoose.set('debug', (collectionName, methodName, ...methodArgs) => {
  Logger.verbose(
    `${collectionName}.${methodName}(${JSON.stringify(methodArgs)})`,
    'Mongoose',
  );
});

@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: '.env',
      isGlobal: true,
      validationSchema: Joi.object({
        MONGO_URI: Joi.string().required(),
        JWT_SECRET: Joi.string().required(),
        GMAIL_USER: Joi.string().required(),
        GMAIL_PASS: Joi.string().required(),
        EMAIL_FROM_ADDRESS: Joi.string().required(),
        PAYPAL_CLIENT_SECRET: Joi.string().required(),
        PAYPAL_CLIENT_ID: Joi.string().required(),
        WEBHOOK_ID: Joi.string().required(),
        AWS_REGION: Joi.string().required(),
        AWS_BUCKET_NAME: Joi.string().required(),
        AWS_ACCESS_KEY_ID: Joi.string().required(),
        AWS_SECRET_ACCESS_KEY: Joi.string().required(),
        FRONTEND_URL: Joi.string().uri().required(),
      }),
    }),
    MongooseModule.forRoot(
      process.env.MONGO_URI as string,
      {
        autoIndex: true,
        autoCreate: true,
      } as MongooseModuleOptions,
    ),
    /* cls module is used for managing Continuation Local Storage (CLS).
    This allows you to store and access data throughout entire lifecycle of a request.
    In this setup, a unique request ID (generated by ulid) is stored in the CLS,
    which can then be used for tracking and debugging purposes. */
    ClsModule.forRoot({
      middleware: {
        mount: true,
        setup: (cls, req, res) => {
          const requestId = ulid();
          cls.set('x-request-id', requestId);
          res.setHeader('X-Request-ID', requestId);
        },
      },
    }),
    ScheduleModule.forRoot(),
    AuthModule,
    UsersModule,
    EmailModule,
    MoviesModule,
    ShowTimesModule,
    PaypalModule,
    BookingModule,
    FeedbacksModule,
    ChatModule,
    S3Module,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
